// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedtheBirthDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedtheBirthDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202107102209207_Seed the BirthDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
